### ISSUE TITLE
Substitute Bell for Hourglass

### ISSUE THREAD

**Issue by GoldenBounty** [megoforce/darkwinds#13]
This can act as both an End to your turn, and also a Start to the Timer for the Opponent's turn.

<img width="1050" alt="screen shot 2018-04-04 at 11 55 15 am" src="https://user-images.githubusercontent.com/6654526/38319403-b0cf241c-37ff-11e8-96e3-cc0d9f0e5066.png">

**Comment by Bdimenbort** [comment]
Also, when the player's time is close to elapsing, give a visual cue.  Such as the Hourglass shaking.
