### ISSUE TITLE
Highlight Card/Avatar when attacking (priority high)

### ISSUE THREAD

**Issue by GoldenBounty** [megoforce/darkwinds#15]
So you know if  #you're attacking a card or the player directly.

<img width="1046" alt="screen shot 2018-04-04 at 12 03 38 pm" src="https://user-images.githubusercontent.com/6654526/38319683-7661a3ee-3800-11e8-8a8b-512daa05b606.png">

**Comment by Bdimenbort** [comment]
Note: Also everything is too close to itself, there needs to be padding between elements (player and opponent cards, cards and the avatar.

It may work better is the cards were off to the side, then we could extend the game board further down.

Thoughts?
