### ISSUE TITLE
Unable to attack Taunting cards

### ISSUE THREAD

**Issue by GoldenBounty** [megoforce/darkwinds#26]
Was playing a match, and my opponent had several Taunt cards, and i was unable to attack any of them due to the error prompt:

<img width="1244" alt="screen shot 2018-04-05 at 11 19 44 am" src="https://user-images.githubusercontent.com/6654526/38375348-fe1dec5c-38c3-11e8-9a5d-736765650199.png">

**Comment by Bdimenbort** [comment]
I haven't played enough matches to know if this is a recurring, but, but it happened in the last match i played

**Comment by explodi** [comment]
Assigned myself to the issue since I was able to replicate

**Comment by rmujica** [comment]
@explodi @GoldenBounty has this been fixed yet?

**Comment by chulini** [comment]
Today morning is fixed this bug!
