### ISSUE TITLE
Text/cards are blurry and not readable

### ISSUE THREAD

**Issue by scardreads** [megoforce/darkwinds#27]
See attached. 
![darkwinds text cards blurry](https://user-images.githubusercontent.com/37882375/38375470-47c0b40c-38c4-11e8-8c08-21ed18f47a30.png)

**Comment by explodi** [comment]
we succesfully migrated all the HTML5 canvas code (2D) to webGL (3D) which allows us to offer better definition when cards are not selected. Also there's better zooming in to the cards for those who have smaller screens and healt/damage ribbons don't shrink with cards when zoomed out.
