### ISSUE TITLE
Quick Match - do we need this?

### ISSUE THREAD

**Issue by scardreads** [megoforce/darkwinds#29]
See attached. 
![darkwinds quick match](https://user-images.githubusercontent.com/37882375/38376430-8512fd0e-38c6-11e8-8164-63166ad761e0.png)

**Comment by rmujica** [comment]
probably we took this idea inadvertently from Overwatch, Ranked Match is where you go to play "for real", if you want to go and play a normal match with real people without the stress of losing your rating points (like to test a deck idea or something) you can go and play a Quick Match.

**Comment by explodi** [comment]
Perhaps renaming "Quick Match" for "Practice Match" will be more appropiate.

**Comment by scardreads** [comment]
Practice Match makes sense. 
If the stats indicate players are using the "Practice Match" feature then it makes sense to leave it. If not, we should pull it out altogether.
