### ISSUE TITLE
Pages cutoff

### ISSUE THREAD

**Issue by scardreads** [megoforce/darkwinds#3]
![pagecutoff2](https://user-images.githubusercontent.com/37882375/38052827-565c03c4-32a0-11e8-82bd-5e7dff98a5e9.png)
![pagecutoff1](https://user-images.githubusercontent.com/37882375/38052828-5671919e-32a0-11e8-975d-40e33a1de362.png)

**Comment by explodi** [comment]
Thanks for your bug report. We fixed it and it's coming later today when we push the next version.
