### ISSUE TITLE
metamask wallet on multiple devices

### ISSUE THREAD

**Issue by srcstg** [megoforce/darkwinds#36]
When I open my metamask wallet in other computer I keep my address, but i don't see my cards, either my friends.

**Comment by explodi** [comment]
Friends are not stored on wallet

**Comment by srcstg** [comment]
fixed, it was cache problems

**Comment by chulini** [comment]
Seems like when you import a metamask wallet from a mnemonic it takes a while between you put the mnemonic and the wallet updates the balance (and tokens).

After metamask ends sync all your cards are fine after refreshing the webpage
