### ISSUE TITLE
Experience points and level

### ISSUE THREAD

**Issue by explodi** [megoforce/darkwinds#39]
Players should get experience points for every win. Players can level up in dungeons&dragons fashion

**Comment by rmujica** [comment]
like overwatch has levels and ranking?

**Comment by GoldenBounty** [comment]
That's a good idea.  We can potentially do something similar to what Clash Royale does with Trophy's.  

We already have a Ranking Leaderboard.  So, for every win, players get more points, for every loss, points are subtracted.  (The larger the discrepancy between player ranking, the more or less points are gained or lost) We would also match players of similar rank.

Also, in Clash Royale, reaching a certain Trophy count unlocks new backgrounds and cards. We could do something similar, for instance certain cards would be unusable to them, until they reach a certain rank.
